"""
Django settings for bitply project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import dj_database_url

try:
    from settings import *
except ImportError as e:
    pass

DEBUG = os.getenv("DEBUG", False)
TEMPLATE_DEBUG = os.getenv("TEMPLATE_DEBUG", False)
SECRET_KEY = os.getenv("SECRET_KEY")

# Update database configuration with $DATABASE_URL.
DB_FROM_ENV = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(DB_FROM_ENV)
